version: '3.8'

services:
  web1:
    build: ./src
    command: uvicorn app.app_code:app --reload --workers 1 --host 0.0.0.0 --port 8000
    volumes:
      - ./src/:/app/
    ports:
      - "8001:8000"
    environment:
      - DATABASE_URL=postgresql://fast_api_app:fast_api_app@db/fast_api_app_pass
    depends_on:
      - db
    deploy:
      resources:
        limits:
          cpus: "1"

  db:
    image: postgres:13.1-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=fast_api_app
      - POSTGRES_PASSWORD=fast_api_app
      - POSTGRES_DB=fast_api_app_pass

    ports:
      - "5432:5432"

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    ports:
      - 8000:8000
    volumes:
      - ./prometheus_folder/prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'


  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - 4000:3000
    volumes:
      - grafana_data:/var/lib/grafana

volumes:
  prometheus_folder:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: ./prometheus_folder
  grafana_data:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: ./grafana_data
  postgres_data:

networks:
  default: 
    name: fast_api_app